## Practice Questions for numpy
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```



In [15]:
import numpy as np

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [7]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
# 1

A = np.array([1, 2, 5, 8, 10, 12])
B = np.array([3, 5, 8, 11, 18, 20])

# Vertical stacking: each array becomes a row in a new 2D array.
vertical_stack = np.vstack((A, B))
print("Vertical Stack: \n", vertical_stack)

horizonal_stack = np.hstack((A,B))
print("\n Horizontal Stack \n", horizonal_stack)

Vertical Stack: 
 [[ 1  2  5  8 10 12]
 [ 3  5  8 11 18 20]]

 Horizontal Stack 
 [ 1  2  5  8 10 12  3  5  8 11 18 20]


In [25]:
#2

common_ele = np.intersect1d(A,B)
print(" \n Common elements are: \n", common_ele)

 
 Common elements are: 
 [5 8]


In [28]:
# 3

number_range = (A>=5) & (A<=10)
print(" numbers in array A in range from 5 to 10 are \n", A[number_range])

 numbers in array A in range from 5 to 10 are 
 [ 5  8 10]


In [37]:
iris_val = iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:, 0] < 5.0) ]
print("The array is: ", iris_val)

The array is:  [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [40]:
import pandas as pd

#1
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [44]:
df_new = df[['Manufacturer', 'Model', 'Type']]

In [51]:
df_new[::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [52]:
#2

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [64]:
df['Min.Price'].isna().values

array([False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False])

In [68]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Min.Price']

0     12.900000
1     29.200000
2     25.900000
3     17.118605
4     17.118605
        ...    
88    16.600000
89    17.600000
90    22.900000
91    21.800000
92    24.800000
Name: Min.Price, Length: 93, dtype: float64

In [69]:
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())
df['Max.Price']

0     18.800000
1     38.700000
2     32.300000
3     44.600000
4     21.459091
        ...    
88    22.700000
89    22.400000
90    23.700000
91    23.500000
92    28.500000
Name: Max.Price, Length: 93, dtype: float64

In [70]:
#3

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [71]:
df.head()

0   1   2   3
0  31  29  32  25
1  10  25  12  22
2  28  36  22  36
3  33  10  28  11
4  24  14  20  17

In [84]:
df['sum_col'] = df.sum(axis=1)
print(df)

     0   1   2   3  sum_col
0   31  29  32  25      234
1   10  25  12  22      138
2   28  36  22  36      244
3   33  10  28  11      164
4   24  14  20  17      150
5   19  26  20  26      182
6   17  33  14  11      150
7   27  20  20  22      178
8   10  22  37  11      160
9   13  37  31  33      228
10  30  31  12  18      182
11  24  23  24  17      176
12  14  12  32  28      172
13  34  13  32  10      178
14  30  24  20  25      198


In [85]:
df[df.sum(axis=1) > 100]

0   1   2   3  sum_col
0   31  29  32  25      234
1   10  25  12  22      138
2   28  36  22  36      244
3   33  10  28  11      164
4   24  14  20  17      150
5   19  26  20  26      182
6   17  33  14  11      150
7   27  20  20  22      178
8   10  22  37  11      160
9   13  37  31  33      228
10  30  31  12  18      182
11  24  23  24  17      176
12  14  12  32  28      172
13  34  13  32  10      178
14  30  24  20  25      198